---
title: "Friction"
---

**Objectives**

- Determine the coefficients of friction.
- Investigate the large forces that can be created by friction.
- Use linear, semilog, and log-log plots to analyze relationships in data.

Friction is a ubiquitous phenomenon in the real world, but it is frequently ignored in
introductory physics courses. Today, we will examine some of the effects of friction.

This lab consists of three major parts

1. Measure the coefficients of static and kinetic friction.
1. Measure the critical angle of an object on an inclined plane.
1. Investigate the force due to friction in a wrapped cord.

**Keep detailed notes.** Record your setup, procedure, data, and observations in your lab
notebook. Data will include tables and plots. In your memo, summarize your findings and discuss
your conclusions.

## Static and Kinetic Friction

Despite the complex interactions that give rise to friction, the force obeys a simple law:
$$f = \mu N.$$
The force due to friction is directly proportional to the normal force acting on an object. The
constant of proportionality, $\mu$, is called the **coefficient of friction.** If an object is
stationary, the constant is called the **coefficient of static friction,** and the formula gives
the maximum force that can be applied before the object starts slipping. If the object is
sliding along, it is called the **coefficient of kinetic friction.** Typically, the coefficient
of kinetic friction is less than the coefficient of static friction: it is harder to get
something moving than it is to keep it going.

Use a spring scale or a force sensor to investigate this relationship for a wooden block.

**Predict.** Before you begin, consider the following questions.

- What will happen to the force required to move the block if you add mass to it?
- What will happen to coefficients of friction if you add mass to the block?
- Will the coefficients change if you turn the block on its side?

**Measure.**

- Determine the coefficients of static friction and kinetic friction for the block.
- Investigate the dependence on mass and orientation of the block.

**Analyze.** Summarize your results and discuss your findings in your lab memo.

## Critical Angle

Direct measurements with a spring scale or force sensor provide one way to measure the
coefficient of friction. A simple alternative is the following.

1. Place an object on a board.
2. Tilt the board until the object starts to slide down.
3. Use Newton's Second Law and trig to calculate the coefficient of friction.

The maximum angle $\theta$ to which you can tilt the ramp before the object starts sliding down
is called the **critical angle.** The maximum value for the coefficient of static friction is
given by
$$\mu = \tan \theta.$$

Test this relationship with the ramps and blocks at your table.

**Predict.** Discuss the following questions before you begin.

- Which will have a larger critical angle on a wooden ramp: wood, rubber, or steel?
- Is there a maximum theoretical value for the critical angle?

**Measure.**

- Measure the critical angle for the wooden block.
- Measure the critical angle of something else. (Your shoe has a rubber sole ...)

**Analyze.** Summarize your results and discuss your findings in your lab memo.

- Is your critical angle for wood consistent with your measurements in Part 1 of this lab?

## Wrapped Cord

In the last portion of today's lab, we will investigate the surprisingly large forces that can
be generated by friction when you wind a cord around a post. Friction between the cord and post
will reduce the force you need to apply to one end of the rope to balance a force applied to the
other end.

**Predict.** Before you make any measurements, consider the following questions.

- Could a $\SI{1}{g}$ mass and a $\SI{1}{kg}$ mass hang in "balance" if the cord were wrapped
  enough times?
- How will the mass required to "balance" a $\SI{200}{g}$ mass depend on the **winding number**
  — the number of times the string is wrapped around the post? Will the required mass go down by
  the same amount each time the string is looped around the post? Or do you expect some other
  relationship?

**Measure.** Explore this relationship. Measure the force $F_n$ required to suspend a fixed mass
when the string is wrapped around the post $n$ times for at least 5 different winding numbers.
More measurements are better.

**Analyze.** Plot your results three different ways and compare your findings with your
predictions.

- Make a **linear plot** of $F_n$ versus $n$.
- Make a **semilog plot** of $\log F_n$ versus $n$.
- Make a **log-log plot** of $\log F_n$ versus $\log n$.

Compare the three plots and test your prediction about the relation between force and winding
number.

## Above and Beyond

The following activities are not required. If you have the time and the inclination, you may
carry out these investigations for extra credit. You are also free to use any of the materials
available in the lab to carry out your own investigations. You need to **keep a record of your
work** (setup, procedure, data, analysis) to get credit for your efforts.

**Phone Book:** The interleaved pages of two telephone books can withstand a surprisingly large
amount of force. Friction between the pages resists an attempt to pull the phone books apart.
Investigate this effect, and carry out a similar analysis to what you did in Part 3. Include a
linear, semilog, and log-log plot of your data.

**Alternate Measurement of $\mu$:** Take data for the wooden block plus 4 additional masses as in
Part 1 of the experiment. Make a plot of Force versus Mass. What relationship do you expect? Use
this data and model to determine the coefficient of static friction.

**Critical Angle:** Take data for the wooden block plus 4 additional masses as in Part 2 of the
experiment. Make a plot of Critical Angle versus Mass. Determine how the critical angle depends
on the mass of the block.

**Modeling:** Construct a mathematical model of the forces generated by the cord. How are the
forces generated? What variables do they depend on? Can you derive an equation from your model
that agrees with your data? Or that you can test in some other way?
