---
title: "Work and Energy"
---

**Objectives**

- Investigate impulse and work.
- Design and carry out an experiment to investigate conservation of energy.

Work describes a transfer of energy between systems. Work can change the kinetic energy of a
system or its potential energy. Although work can transfer energy between systems, Newton's laws
imply that the total energy in the universe is conserved. This yields the work-energy theorem:
$W = \Delta K + \Delta U.$

This lab consists of two parts.

1. Investigate impulse, work, and energy with a motion cart.
1. Design and carry out an experiment to investigate conservation of energy.

**Keep detailed notes.** Record your setup, procedure, data, and observations in your lab
notebook. Data will include tables and plots. In your memo, summarize your findings and discuss
any conclusions you draw from your data.

## Impulse, Work, and Energy

Some of the motion carts in the lab are equipped with a launcher. The launcher provides a
reasonably reproducible force each time it is used.

Discuss the following questions with your group before you begin taking measurements.

- How can you measure the ___impulse___ $\vec{J}$ generated by the launcher?
- How can you measure the ___work___ $W$ done by the launcher?
- Do you think the launcher delivers the same impulse each time it is used?
- Do you think the launcher does the same amount of work each time it is used?
- If you double the mass of a cart, what will happen to the final speed of the cart?
- What would a plot of final velocity versus mass look like?

Use a motion cart to measure the impulse and work for at least five different cart masses. Take
multiple measurements for each mass and make your best estimate of the impulse and work generated
by the launcher.

**Make a plot of final velocity versus mass of the cart.**

- Did the launcher deliver the same impulse each time it was used?
- Did the launcher do the same work each time it was used?

## Conservation of Energy

The principle of conservation of energy is this:
___The total energy in a closed system is constant.___

Work with your lab group to design an experiment to investigate the conservation of energy.
Your experiment should include the following elements.

- A system in which both potential and kinetic energy can change
- A theoretical prediction that you can test with measurements
- A numerical test of conservation of energy

**Keep a good record of your work.** Someone reading your notebook should be able to replicate
your work and verify your findings.
